baseurl = "http://bepsays.com/"
title = "bepsays.com"
languageCode = "no-nn"
metaDataFormat = "yaml"
newContentEditor = "mate"
pygmentsStyle = "trac"
canonifyUrls = "true"
pluralizeListTitles = "false"
pygmentsCodeFences = "true"
paginatePath = "side"
enableEmoji = true
paginate = 6
defaultContentLanguage = "nn"
defaultContentLanguageInSubdir = false
sectionPagesMenu = "sect"

disqusShortname = "bepsays"

# Note: This can also be set per language.
# Every Page Kind without a definition here will be assigned the HTML output format.
# Also note that the outputs section in Page front matter will override any setting in here.
[outputs]
home = [ "HTML", "CSS" ]
# home = [ "HTML", "AMP", "RSS", "JSON", "MyEnrichedFormat"]
# page = [ "HTML"]

[blackfriday]
angledQuotes = true
hrefTargetBlank = true

[permalinks]
  pol = "/:year/:month/:day/:slug/"
  fun = "/:year/:month/:day/:slug/"
  art = "/:year/:month/:day/:slug/"
  tec = "/:year/:month/:day/:slug/"

[taxonomies]
    tag = "tags"
    series = "series"

[params]
description = "bepsays.com. Om dette og hint."
[params.colors]
main = "green"

# The media types and output format definitions below are just for testing/demo purpose.
[mediaTypes]
[mediaTypes."text/enriched"]
suffix = "enr"

[outputFormats]
# Not sure what the Enriched format is, but this will produce a plain text Home page with URL bep://bepsays.com/myindex.enr
[outputFormats.MyEnrichedFormat]
mediaType = "text/enriched" # Matched by Type in the mediaTypes set.
baseName = "myindex"
isPlainText = true
protocol = "bep://"

[languages]
[languages.nn]
languageName = "Nynorsk"
weight = 1
title = "Bepsays p√• norsk"

[languages.en]
languageName = "English"
weight = 2
title = "Bepsays in English"
paginatePath = "page"
description = "bepsays.com. Abut this and that."
[languages.en.blackfriday]
angledQuotes = false
hrefTargetBlank = true
[languages.en.mediaTypes]
[languages.en.mediaTypes."application/xhtml"]
suffix = "xml"

